AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS REST API with CORS

Outputs:

  StackRegion:
    Value: !Ref AWS::Region
  ItemTableName:
    Value: !Ref ItemTable
  ItemsFnCreateArn:
    Value: !GetAtt ItemsFnCreate.Arn
  ItemsFnIndexArn:
    Value: !GetAtt ItemsFnIndex.Arn

Resources:

  ############
  ## TABLES ##
  ############

  ItemTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Name
        Type: String

  ###############
  ## Functions ##
  ###############

  ItemsFnPreflight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/items.preflight
      Runtime: nodejs6.10
      CodeUri: ./package/aws-cors-api.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ITEM_TABLE: !Ref ItemTable
      Events:
        OptionsItems:
          Type: Api
          Properties:
            Method: OPTIONS
            Path: /items
        OptionsItem:
          Type: Api
          Properties:
            Method: OPTIONS
            Path: /items/{itemName}

  ItemsFnCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/items.create
      Runtime: nodejs6.10
      CodeUri: ./package/aws-cors-api.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ITEM_TABLE: !Ref ItemTable
      Events:
        PostItems:
          Type: Api
          Properties:
            Method: POST
            Path: /items

  ItemsFnIndex:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/items.index
      Runtime: nodejs6.10
      CodeUri: ./package/aws-cors-api.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ITEM_TABLE: !Ref ItemTable
      Events:
        GetItems:
          Type: Api
          Properties:
            Method: GET
            Path: /items

  ItemsFnShow:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/items.show
      Runtime: nodejs6.10
      CodeUri: ./package/aws-cors-api.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ITEM_TABLE: !Ref ItemTable
      Events:
        GetItem:
          Type: Api
          Properties:
            Method: GET
            Path: /items/{itemName}

  ItemsFnUpdate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/items.update
      Runtime: nodejs6.10
      CodeUri: ./package/aws-cors-api.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ITEM_TABLE: !Ref ItemTable
      Events:
        PutItem:
          Type: Api
          Properties:
            Method: PUT
            Path: /items/{itemName}
        PatchItem:
          Type: Api
          Properties:
            Method: PATCH
            Path: /items/{itemName}

  ItemsFnDestroy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/items.destroy
      Runtime: nodejs6.10
      CodeUri: ./package/aws-cors-api.zip
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          ITEM_TABLE: !Ref ItemTable
      Events:
        DeleteItem:
          Type: Api
          Properties:
            Method: DELETE
            Path: /items/{itemName}
